---
- name: Echo hostname playbook
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: Hello World!
    - name: echo token
      debug:
        msg: url '{{ url }}'
    - name: echo secret value
      debug:
        msg:  "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/tf_secret token='{{ token }}' 'namespace=admin' url='{{ url }}'') }}"
